version: "3.8"

services:
  db1:
    image: mysql:8.0
    container_name: mysql-db-bookingservice
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_DATABASE: "booking_db"
    ports:
      - "3307:3306"  
    volumes:
      - db1-data:/var/lib/mysql

  db2:
    image: mysql:8.0
    container_name: mysql-db-playermanagementservice
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_DATABASE: "player_db"
    ports:
      - "3308:3306"  
    volumes:
      - db2-data:/var/lib/mysql

  db3:
    image: mysql:8.0
    container_name: mysql-db-battleservice
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_DATABASE: "battle_db"
    ports:
      - "3309:3306" 
    volumes:
      - db3-data:/var/lib/mysql

  activemq:
    image: rmohr/activemq
    ports:
      - "61613:61613"  
      - "8161:8161"     
    environment:
      ACTIVEMQ_HOST: localhost
      ACTIVEMQ_PORT: 61613
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSCODE: admin

  web-gateway:
    build:
      context: ./APIGateway/web-gateway
      dockerfile: Dockerfile
    container_name: web-gateway
    ports:
      - "8080:8080"
    depends_on:
      - playermanagementservice
      - bookingservice
      - battle-simulation
    environment:
      GATEWAY_PORT: 8080

  battle-simulation:
    build:
      context: ./BattleSimulationService
    ports:
      - "7000:7000"
    depends_on:
      - activemq
      - db3
    environment:
      DB_HOST: battleservice-battleservice.j.aivencloud.com
      DB_PORT: 28148
      DB_USERNAME: avnadmin
      DB_PASSWORD: AVNS_kAk_pQN6MIBlYh9_2PH
      DB_NAME: defaultdb
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61613
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSCODE: admin

  bookingservice:
    build:
      context: ./BookingService/src
      dockerfile: Dockerfile
    container_name: bookingservice
    ports:
      - "5050:5050"
    depends_on:
      - db1
    environment:
      DB_HOST: booking-service-shipping-service.h.aivencloud.com
      DB_PORT: 28763
      DB_USERNAME: avnadmin
      DB_PASSWORD: AVNS_VAELPrEt63Oao1GG7Nd
      DB_NAME: defaultdb
      JWT_SECRET: your_jwt_secret_key

  playermanagementservice:
    build:
      context: ./PlayerManagementService
      dockerfile: Dockerfile
    container_name: playermanagementservice
    ports:
      - "5000:5000"
    depends_on:
      - db2
    environment:
      DB_HOST: player-management-service-vodenje-dopustov.j.aivencloud.com
      DB_PORT: 23077
      DB_USERNAME: avnadmin
      DB_PASSWORD: AVNS_2NGnw_d0-Hv_KnDO05V
      DB_NAME: defaultdb
      JWT_SECRET: your_jwt_secret_key

  frontend:
    build:
      context: ./WebUI
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:3001"
    environment:
      API_GATEWAY: http://web-gateway:8080
    depends_on:
      - web-gateway

volumes:
  db1-data:
  db2-data:
  db3-data: