name: Run Unit Tests for Battle Service

on:
  push:
    branches:
      - main
      - master
      - develop
      - feature/**

jobs:
  test-battle-service:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./BattleSimulationService

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Setup .env file for test DB
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env
          echo "DB_NAME=test_db" >> .env
          echo "JWT_SECRET_KEY=githubactionsecret" >> .env

      - name: Run unit tests
        run: npm run test